version: '3.8'

services:
  yt-dlp-api:
    build: .
    container_name: yt_dlp_api
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
  celery_worker:
    build: .
    container_name: yt_dlp_celery_worker
    command: ["/app/worker-entrypoint.sh"]
    depends_on:
      - redis
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
